@startuml

()datalayer

()core

()induction

()grammar_statistics

()rule_adding

()grammar_estimator

()evolution

()induction

package algorithm {
    [gcs_runner]
    gcs_runner ..> grammar_statistics
    gcs_runner ..> core
    gcs_runner ..> rule_adding
    gcs_runner ..> grammar_estimator
    gcs_runner ..> evolution
    gcs_runner ..> induction

    [run_estimator]

    [gcs_simulator]
    gcs_simulator ..> datalayer
    gcs_simulator ..> run_estimator
    gcs_simulator ..> gcs_runner
    gcs_simulator ..> core

    [task_model]
}

@enduml
