@startuml

!include core.wsdi
hide RulePopulation
hide Rule
hide TerminalRule
hide Symbol
hide RulePopulationAccessViolationError

!include production.wsdi
hide EmptyProduction

!include environment.wsdi

package environment #FFFFFF {

class CykTableIndexError

class Environment
Environment : with_viterbi_approach(sentence, factory)
Environment : with_baum_welch_approach(sentence, factory)
Environment : __init__(self, sentence, factory)
Environment : probability_approach
Environment : get_symbols(self, absolute_coordinates)
Environment : add_production(self, production)
Environment : get_left_parent_symbol_count(self, coordinates_with_shift)
Environment : get_right_parent_symbol_count(self, coordinates_with_shift)
Environment : get_row_length(self, row)
Environment : get_sentence_length(self)
Environment : is_sentence_positive(self)
Environment : validate_absolute_coordinates(self, coordinates)
Environment : get_sentence_symbol(self, index)
Environment : get_last_cell_productions(self)
Environment : get_detector_symbols(self, coord)
Environment : get_unsatisfied_detectors(self, coordinates)
Environment : has_no_productions(self, coordinates)
Environment : get_child_productions(self, production)
Environment : simple_get_child_productions(self, production)
Environment --* Sentence
Environment ..> ProductionPool: creates(factory)
Environment ..> Production: uses
Environment --> CykTableIndexError: raises

}

@enduml
