@startuml

[data_layer]

[core]
core <..> data_layer

[utils]
utils <.. core
[grammar_statistics]
[rule_adding]

package induction {

    [coverage_operators]
    [cyk_executors]
    [cyk_service]
    [detector]
    [environment]
    [grammar_corrector]
    [production]
    [traceback]

    coverage_operators <-->  cyk_service
    cyk_executors <--> cyk_service
    cyk_service --> environment
    cyk_service --> grammar_corrector
    traceback <-->  cyk_service

    coverage_operators ..> detector
    coverage_operators ..> core
    coverage_operators ..> production
    coverage_operators ..> environment


    cyk_executors ..> detector
    cyk_executors ..> core
    cyk_executors ..> coverage_operators
    cyk_executors ..> environment

    detector <..> production
    detector ..> core

    environment ..> core
    environment ..> production

    grammar_corrector ..> core
    grammar_corrector ..> grammar_statistics

    production ..> core

    traceback ..> core
    traceback ..> grammar_statistics
    traceback ..> environment
    traceback ..> cyk_executors

    grammar_statistics ..> utils
    grammar_statistics ..> core
    grammar_statistics ..> cyk_executors
    grammar_statistics ..> production

    rule_adding ..> utils
    rule_adding ..> core
    rule_adding ..> grammar_statistics
}

@enduml
