@startuml

!include utils.wsdi

!include core.wsdi
hide Sentence
hide TerminalRule

!include grammar_statistics.wsdi
hide RuleInfo
hide RuleStatistics
hide PasiekaRuleInfo
hide PasiekaLeftSideInfo
hide PasiekaRuleStatistics
hide Fitness
hide PasiekaFitness
hide ClassicRuleInfo
hide ClassicRuleUsageInfo
hide ClassicRuleStatistics
hide StatisticsVisitor
hide ClassicFitness
hide DummyCykStatistics

package rule_adding {

    enum AddingRuleStrategyHint {
        expand_population = 0
        control_population_size = 1
        control_population_size_with_elitism = 2
    }

    class AddingRuleStrategy
    AddingRuleStrategy : hints
    AddingRuleStrategy : apply(self, adding_supervisor, statistics, rule, rule_population)
    AddingRuleStrategy : is_applicable(self, strategy_hint)

    class SimpleAddingRuleStrategy
    SimpleAddingRuleStrategy --|> AddingRuleStrategy

    class AddingRuleWithCrowdingStrategy
    AddingRuleWithCrowdingStrategy --|> AddingRuleStrategy

    class AddingRuleWithElitismStrategy
    AddingRuleStrategy : elite
    AddingRuleStrategy : generate_elite(self, adding_supervisor, statistics, rule_population)
    AddingRuleWithElitismStrategy --|> AddingRuleStrategy

    class AddingRuleSupervisor
    AddingRuleSupervisor : get_default_strategies()
    AddingRuleSupervisor : __init__(self, randomizer, configuration, strategies)
    AddingRuleSupervisor : add_rule(self, rule, rule_population, statistics, strategy_hint=AddingRuleStrategyHint.expand_population)
    AddingRuleSupervisor --* Randomizer
    AddingRuleSupervisor --* AddingRulesConfiguration
    AddingRuleSupervisor "1" --o "0..*"  AddingRuleStrategy
    AddingRuleSupervisor ..> Rule: uses
    AddingRuleSupervisor ..> RulePopulation: uses
    AddingRuleSupervisor ..> GrammarStatistics: uses
    AddingRuleSupervisor --> AddingRuleStrategyHint: uses

    class AddingRulesConfiguration
    AddingRulesConfiguration : crowding
    AddingRulesConfiguration : elitism
    AddingRulesConfiguration ..* CrowdingConfiguration: uses
    AddingRulesConfiguration ..* ElitismConfiguration: uses

    class CrowdingConfiguration
    CrowdingConfiguration : factor
    CrowdingConfiguration : size

    class ElitismConfiguration
    ElitismConfiguration : is_used
    ElitismConfiguration : size
}

@enduml